
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int EXTERN = 29;
  public static final int IDENT = 30;
  public static final int ELSE = 22;
  public static final int CONSTSTRING = 28;
  public static final int PLUS = 3;
  public static final int NOTEQ = 12;
  public static final int RBRACE = 26;
  public static final int RPARENS = 23;
  public static final int WHILE = 18;
  public static final int SEMI = 2;
  public static final int RETURN = 20;
  public static final int GREATER = 15;
  public static final int GREATEQ = 13;
  public static final int IF = 21;
  public static final int MODULO = 7;
  public static final int LBRACE = 25;
  public static final int SHIFTLEFT = 8;
  public static final int DO = 19;
  public static final int LPARENS = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int CONSTINT = 27;
  public static final int SHIFTRIGHT = 9;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 10;
  public static final int LESSEQ = 14;
  public static final int EQEQ = 11;
  public static final int FOR = 17;
  public static final int LESS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODULO",
  "SHIFTLEFT",
  "SHIFTRIGHT",
  "EQ",
  "EQEQ",
  "NOTEQ",
  "GREATEQ",
  "LESSEQ",
  "GREATER",
  "LESS",
  "FOR",
  "WHILE",
  "DO",
  "RETURN",
  "IF",
  "ELSE",
  "RPARENS",
  "LPARENS",
  "LBRACE",
  "RBRACE",
  "CONSTINT",
  "CONSTSTRING",
  "EXTERN",
  "IDENT"
  };
}

